### ISSUE TITLE
Accommodate Timetable card for 2 types of timetable

### ISSUE THREAD

**Issue by Chinmay-KB** [developer-student-clubs-nitr/project-avocado#49]
Currently, the app only serves regular timetable, while leaving out the tutorial class timetable. The app should be modified to accommodate both the timetables and designed accordingly

On clicking the "Timetable" card, it splits into two, one for the normal timetable and the other for tutorial classes. Clicking the respective card leads to respective timetables.

**Comment by DesignrKnight** [comment]
Fix in #50
