### ISSUE TITLE
Id card image upload

### ISSUE THREAD

**Issue by ankank30** [developer-student-clubs-nitr/project-avocado#57]
**Is your feature request related to a problem? Please describe.**
Many users books an appointment without actual intention.

**Describe the solution you'd like**
Making the booking process tougher.

**Additional context**
The users now need to upload their Id card image so that only verified and intentional user books an appointment.

Later one can even introduce ML kit to verify the users are genuine.

**Comment by DesignrKnight** [comment]
Fixed by @ankank30
